substitutions:
  name: xiao-ble-proxy-bermuda
  friendly_name: "XIAO BLE Proxy Bermuda"
  comment: "XIAO ESP32C6 BLE Proxy optimized for Bermuda"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password
  api_key: !secret api_encryption_key

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}

# ESP32-C6 configuration optimized for stability
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_FREERTOS_UNICORE: y

logger:
  level: INFO
  baud_rate: 115200

api:
  encryption:
    key: ${api_key}

ota:
  password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true
  
  # Enable fallback hotspot
  ap:
    ssid: "${name}-fallback"
    password: "bermuda123"

captive_portal:

# Bluetooth proxy for Bermuda
bluetooth_proxy:
  active: true

# BLE tracker with Bermuda-optimized settings
esp32_ble_tracker:
  scan_parameters:
    continuous: true
    active: true
    interval: 320ms
    window: 300ms

# Basic diagnostic sensors
sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    entity_category: config