substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  name: xiao-ble-proxy-working
  friendly_name: "XIAO BLE Proxy Working"
  comment: "XIAO ESP32C6 BLE Proxy based on working example"
  name_add_mac_suffix: "True"
  baud_rate: "0"
  ble_interval: 320ms
  ble_window: 300ms
  proxy_active_scan: "True"
  ota_pw: !secret ota_password 
  api_key: !secret api_encryption_key
  beacon_uuid: "59E0D1DA-AF5D-47C3-AB2D-2F166DEAD901"
  beacon_major: "42069"
  beacon_minor: "1001"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: ${name_add_mac_suffix}

# ESP32-C6 configuration matching working example
esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4mb
  variant: esp32c6
  framework:
    type: esp-idf
    # Let ESPHome choose the versions
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # BLE specific optimizations from working example
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

logger:
  baud_rate: ${baud_rate}

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}
  # Start BLE scanning only when connected to HA
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Stop BLE scanning when disconnected
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
    password: ${ota_pw}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: True
  manual_ip:
    static_ip: 192.168.1.201
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XIAO-BLE-Proxy-Working"
    password: "123456789abc"

captive_portal:

# Bluetooth proxy configuration
bluetooth_proxy:
  active: True

# BLE tracker with optimized settings
esp32_ble_tracker:
  scan_parameters:
    continuous: True
    active: ${proxy_active_scan}
    interval: ${ble_interval}
    window: ${ble_window}

# iBeacon for location reference
esp32_ble_beacon:
  type: iBeacon
  uuid: ${beacon_uuid}
  major: ${beacon_major}
  minor: ${beacon_minor}

# Diagnostic sensors
sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

# Diagnostic text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic

# Control buttons
button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    entity_category: config

# Safe mode for recovery
safe_mode: