substitutions:
  name: xiao-bare-minimum
  friendly_name: "XIAO Bare Minimum"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Most minimal ESP32-C6 configuration possible
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 115200

# No intervals, no components, just basic logging