substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  name: xiao-ble-proxy2
  friendly_name: "XIAO BLE Proxy 2 - Dining Room"
  comment: "XIAO ESP32C6 BLE Proxy optimized for Bermuda - Dining Room"
  name_add_mac_suffix: "False"  # Disable MAC suffix to avoid Bermuda confusion
  baud_rate: "0"  # Disable serial logging for better performance
  ble_interval: 320ms
  ble_window: 300ms
  proxy_active_scan: "True"
  ota_pw: !secret ota_password 
  api_key: !secret api_encryption_key
  beacon_uuid: "59E0D1DA-AF5D-47C3-AB2D-2F166DEAD901"
  beacon_major: "42069"
  beacon_minor: "1002"  # Unique minor for proxy 2

# packages:
#   Bermuda.include_minimal: github://agittins/bermuda-proxies/packages/bermuda-proxy-esp32-c3-minimal.yaml
# Note: Commented out due to git permission issues, using inline configuration instead

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: ${name_add_mac_suffix}

# ESP32-C6 specific configuration
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # BLE optimization options from Bermuda
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y  # For C6 devices
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
    # version: 5.3.1  # Use recommended version
    # platform_version: 6.9.0  # Use recommended version

# ADC component fix for ESP32-C6 (disabled due to git permission issues)
# external_components:
#   - source:
#       type: git
#       url: https://github.com/lboue/esphome
#       ref: adc_oneshot
#     components: [ adc ]
#     refresh: 0s

logger:
  baud_rate: ${baud_rate}

# Home Assistant API with optimized BLE control
api:
  encryption:
    key: ${api_key}
  # Start BLE scanning only when connected to HA
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Stop BLE scanning when disconnected
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  password: ${ota_pw}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: True
  manual_ip:
    static_ip: 192.168.1.202  # Unique IP for proxy 2
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

# Bluetooth proxy configuration
bluetooth_proxy:
  active: True

# BLE tracker with Bermuda-optimized settings (fixed for metadevices issue)
esp32_ble_tracker:
  scan_parameters:
    continuous: False  # Don't auto start, control via API
    active: ${proxy_active_scan}
    interval: ${ble_interval}
    window: ${ble_window}

# iBeacon disabled - conflicts with esp32_ble_tracker
# esp32_ble_beacon:
#   type: iBeacon
#   uuid: ${beacon_uuid}
#   major: ${beacon_major}
#   minor: ${beacon_minor}

# Diagnostic sensors
sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

# Diagnostic text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic

# Control buttons
button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    entity_category: config

# Safe mode for recovery (enabled via button above)