substitutions:
  name: xiao-ultra-minimal
  friendly_name: "XIAO Ultra Minimal"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Minimal ESP32-C6 configuration - try different board
esp32:
  board: esp32-c6-devkitm-1  # Different board variant
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 115200

# Absolutely minimal - just log messages
interval:
  - interval: 3s
    then:
      - logger.log: "Minimal test - still alive"