substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  name: xiao-wifi-only
  friendly_name: "XIAO WiFi Only Test"
  api_key: !secret api_encryption_key
  ota_pw: !secret ota_password 

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# ESP32-C6 configuration
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0  # Disable serial to free resources

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_pw}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: True
  manual_ip:
    static_ip: 192.168.1.201
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot
  ap:
    ssid: "XIAO-WiFi-Test"
    password: "123456789abc"

captive_portal:

# Simple status indicators
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

# Heartbeat to show it's working
interval:
  - interval: 30s
    then:
      - logger.log: "Device is alive and connected"