substitutions:
  name: xiao-bootloader-safe
  friendly_name: "XIAO Bootloader Safe"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Conservative ESP32C6 settings for bootloader compatibility
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      # Safe flash settings for XIAO
      CONFIG_ESPTOOLPY_FLASHMODE_DIO: y
      CONFIG_ESPTOOLPY_FLASHFREQ_40M: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      # Disable all watchdogs
      CONFIG_ESP_TASK_WDT_EN: n
      CONFIG_ESP_INT_WDT_EN: n
      CONFIG_ESP_SYSTEM_CHECK_INT_LEVEL_4: n
      # Conservative memory settings
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "3584"
      CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "2304"

logger:
  level: INFO
  baud_rate: 115200

# Minimal test - no intervals to avoid any timing issues