substitutions:
  name: xiao-seeed-board
  friendly_name: "XIAO Seeed Board"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

# Try using the XIAO-specific board definition
esp32:
  board: seeed_xiao_esp32c6
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 115200

# Just basic heartbeat
interval:
  - interval: 5s
    then:
      - logger.log: "XIAO Seeed board test"