esphome:
  name: reserviorsensor
  friendly_name: reserviorsensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key  # Use a secret

ota:
  platform: esphome  # Correct platform for OTA
  password: !secret ota_password  # Use a secret

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.122  # Replace with an available IP in your network
    gateway: 192.168.1.1  # Replace with your router's IP
    subnet: 255.255.255.0  # Usually this value
  # Enable fallback hotspot (if needed)
  ap:
    ssid: "reserviorsensor"
    password: !secret ap_password  # Replace with your password

one_wire:  # Two spaces
  - platform: gpio  # Four spaces
    pin: GPIO13  # Six spaces

# Time component (essential for timestamps)
time:
  - platform: sntp
    id: reservoir_clock  # Changed the id to avoid conflict

# Combined Sensor Section
sensor:
  - platform: ultrasonic
    trigger_pin: GPIO17
    echo_pin: GPIO16
    timeout: 2m
    pulse_time: 20us
    update_interval: 60s
    name: "Reservoir Depth"
    unit_of_measurement: "gal"  # Or "cm" if you want depth only
    accuracy_decimals: 4
    filters:
      - filter_out: nan
      - lambda: |
          // Calculate water level in cm
          float water_level_cm = 40.85 - (x * 100);  // Simplified calculation

          // Ensure water level is within valid range (0 to bucket height)
          water_level_cm = std::max(0.0f, std::min(water_level_cm, 40.85f));

          // Calculate water volume in gallons
          float water_volume_gal = PI * pow(29.21 / 2.0, 2) * water_level_cm * 0.000264172;

          return water_volume_gal;  // Or return water_level_cm for depth

   

  - platform: dallas_temp
    id: res_water_temp
    name: "Reservoir Water Temp"
    filters:
      - filter_out: nan
      - lambda: return x * (9.0 / 5.0) + 32.0;  # Convert to Fahrenheit
    unit_of_measurement: "°F"
    accuracy_decimals: 2